version: "3"
services:
  api:
    build: .
    depends_on:
    - postgres
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/usr/src/app:ro
    env_file:
      - ./.env

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432

    volumes:
      - postgres-db:/var/lib/postgresql/data
  
volumes:
  postgres-db: